### ISSUE TITLE
write errors: stdout

### ISSUE THREAD

**Issue by sranger22** [vlmantova/bookml#13]
Errors reported using gmake & bookml.mk for versions 0.6 and 0.7. For example, for file template.tex:

gmake[2]: 'auxdir/template.pdf' is up to date.
gmake[2]: write error: stdout
bookml/bookml.mk:361: auxdir/template.resources.d: No such file or directory
gmake[1]: *** [bookml/bookml.mk:330: auxdir/template.pdf] Error 1
gmake[1]: *** Deleting file 'auxdir/template.pdf'
gmake[1]: *** [auxdir/template.pdf] Deleting file 'auxdir/template.pdf.d'
gmake: *** [bookml/bookml.mk:353: template/index.html] Error 2
gmake: write error: stdout

No errors with version 0.5. Possible to proceed to some extent with 0.7 by removing the Delete upon errors statements, though it requires multiple gmake runs.

**Comment by xworld21** [comment]
My bad, I should have tested the new changes in Windows.

**Comment by sranger22** [comment]
No problem, thanks for fixing it so quickly - I knew it was to do with writing to the files in Windows but didn't have the skills to fix it! 
Still new to BookML but it looks like a great piece of code to make LateXML more straightforward!
