### ISSUE TITLE
Nothing generated 

### ISSUE THREAD

**Issue by hayden-MB** [vlmantova/bookml#29]
On attempting to conver some notes but just get the message `make: Nothing to be done for 'all'.`

I am really struggling to understand why a document I have is not triggering the conversion. It has `\documentclass[11pt,dvipsnames]{book}` in so I would have thought it would throw an error rather than simply not running anything.

Sorry this isn't very useful but I don't know what is relevant.

**Comment by xworld21** [comment]
Does the file have a space in the name?

**Comment by xworld21** [comment]
Duplicate #19. I really need to throw a warning!
